// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXj0y27eoWgwDtQ-Uxm7-9I8kFeTHFCA0',
    appId: '1:685919055288:web:16ea1654dda780ef0d334d',
    messagingSenderId: '685919055288',
    projectId: 'rdp-todolist3',
    authDomain: 'rdp-todolist3.firebaseapp.com',
    storageBucket: 'rdp-todolist3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmalF2LFwyGkD_VCZnKF2wA2BUuxtAEcw',
    appId: '1:685919055288:android:1ca28cca8a5c0e770d334d',
    messagingSenderId: '685919055288',
    projectId: 'rdp-todolist3',
    storageBucket: 'rdp-todolist3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCInrk-9yJGf5O0bW2nUTUfExVRvS0YJyo',
    appId: '1:685919055288:ios:abe003cd0c7bafdb0d334d',
    messagingSenderId: '685919055288',
    projectId: 'rdp-todolist3',
    storageBucket: 'rdp-todolist3.appspot.com',
    iosBundleId: 'com.example.rdpTodolist3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCInrk-9yJGf5O0bW2nUTUfExVRvS0YJyo',
    appId: '1:685919055288:ios:abe003cd0c7bafdb0d334d',
    messagingSenderId: '685919055288',
    projectId: 'rdp-todolist3',
    storageBucket: 'rdp-todolist3.appspot.com',
    iosBundleId: 'com.example.rdpTodolist3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXj0y27eoWgwDtQ-Uxm7-9I8kFeTHFCA0',
    appId: '1:685919055288:web:f823d00ccf62f89b0d334d',
    messagingSenderId: '685919055288',
    projectId: 'rdp-todolist3',
    authDomain: 'rdp-todolist3.firebaseapp.com',
    storageBucket: 'rdp-todolist3.appspot.com',
  );

}