// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsnvt0ztfHLRXdiAWJAynJLNJQJf3mmsg',
    appId: '1:17792744799:web:d9c7847e414c826e214aea',
    messagingSenderId: '17792744799',
    projectId: 'rdp-78ed7',
    authDomain: 'rdp-78ed7.firebaseapp.com',
    databaseURL: 'https://rdp-78ed7-default-rtdb.firebaseio.com',
    storageBucket: 'rdp-78ed7.appspot.com',
    measurementId: 'G-DVH8SYWHTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBov9aNeMnpxe1_0i49C5HiK43_fMhoBlU',
    appId: '1:17792744799:android:098ce879685dcd4b214aea',
    messagingSenderId: '17792744799',
    projectId: 'rdp-78ed7',
    databaseURL: 'https://rdp-78ed7-default-rtdb.firebaseio.com',
    storageBucket: 'rdp-78ed7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj818xwvWAFrvyelU9Q8pYxWqfpsj04M4',
    appId: '1:17792744799:ios:16e7e6a024d0ddad214aea',
    messagingSenderId: '17792744799',
    projectId: 'rdp-78ed7',
    databaseURL: 'https://rdp-78ed7-default-rtdb.firebaseio.com',
    storageBucket: 'rdp-78ed7.appspot.com',
    iosBundleId: 'com.example.rdpTodolist3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj818xwvWAFrvyelU9Q8pYxWqfpsj04M4',
    appId: '1:17792744799:ios:16e7e6a024d0ddad214aea',
    messagingSenderId: '17792744799',
    projectId: 'rdp-78ed7',
    databaseURL: 'https://rdp-78ed7-default-rtdb.firebaseio.com',
    storageBucket: 'rdp-78ed7.appspot.com',
    iosBundleId: 'com.example.rdpTodolist3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsnvt0ztfHLRXdiAWJAynJLNJQJf3mmsg',
    appId: '1:17792744799:web:2e4b521c729be63e214aea',
    messagingSenderId: '17792744799',
    projectId: 'rdp-78ed7',
    authDomain: 'rdp-78ed7.firebaseapp.com',
    databaseURL: 'https://rdp-78ed7-default-rtdb.firebaseio.com',
    storageBucket: 'rdp-78ed7.appspot.com',
    measurementId: 'G-L3TPYC29BC',
  );

}